language: c

before_script:
  - wget http://saffire-lang.org/travis/libicu-dev_4.8.1.1-3_amd64.deb
  - wget http://saffire-lang.org/travis/libicu48_4.8.1.1-3_amd64.deb
  - sudo dpkg -i libicu48_4.8.1.1-3_amd64.deb
  - sudo dpkg -i libicu-dev_4.8.1.1-3_amd64.deb
  - sudo mkdir -p /usr/share/saffire/modules
  - sudo ln -s `pwd`/sfl /usr/share/saffire/modules/sfl

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcre3-dev libfcgi-dev libedit-dev libbz2-dev libxml2-dev
  - sudo apt-get install -qq php5-cli php-pear
  - sudo apt-get install -qq libcunit1-dev
  - printf "\n" | sudo pecl install yaml
  - sudo sh -c 'echo "extension = yaml.so" >> /etc/php5/cli/php.ini'

# Compile on gcc and clang
compiler:
  - clang
  - gcc
  
# Separate debug and release targets
env:
  - TARGET=debug
  - TARGET=release

# Build target. But only on release target, we can run our unit-tests
script: ./build.sh -t $TARGET -t && (SAFFIRE_TEST_BIN=build/release/saffire sh unittest.sh || true)

notifications:
  irc: "irc.freenode.org#saffire"
